// AUTO-GENERATED by scripts/build-overnight-pages.js — do not edit by hand.
// Overnight DB pages exist in en (no prefix) + fr/de/zh dirs. lastmod = database 'updated'.
export const OVERNIGHT_LASTMOD = "2026-07-27";
export const OVERNIGHT_URLS = [
  "/overnight-parking/michi-no-eki/",
  "/overnight-parking/michi-no-eki/fukuoka/",
  "/overnight-parking/michi-no-eki/saga/",
  "/overnight-parking/michi-no-eki/nagasaki/",
  "/overnight-parking/michi-no-eki/kumamoto/",
  "/overnight-parking/michi-no-eki/oita/",
  "/overnight-parking/michi-no-eki/miyazaki/",
  "/overnight-parking/michi-no-eki/kagoshima/",
  "/overnight-parking/michi-no-eki/fukuoka/munakata/",
  "/overnight-parking/michi-no-eki/fukuoka/oki/",
  "/overnight-parking/michi-no-eki/nagasaki/sonogi-no-sho/",
  "/overnight-parking/michi-no-eki/kumamoto/asobo-no-sato-kugino/",
  "/overnight-parking/michi-no-eki/kumamoto/kikusui/",
  "/overnight-parking/michi-no-eki/kumamoto/ariake-rippleland/",
  "/overnight-parking/michi-no-eki/kumamoto/miyajidake-kakashi-no-sato/",
  "/overnight-parking/michi-no-eki/kumamoto/mizube-plaza-kamoto/",
  "/overnight-parking/michi-no-eki/kumamoto/wellness-arao/",
  "/overnight-parking/michi-no-eki/kumamoto/komoriuta-no-sato-itsuki/",
  "/overnight-parking/michi-no-eki/kumamoto/nishiki/",
  "/overnight-parking/michi-no-eki/kumamoto/toyo/",
  "/overnight-parking/michi-no-eki/miyazaki/miyakonojo-niqll/",
  "/overnight-parking/michi-no-eki/kumamoto/namino/",
  "/overnight-parking/michi-no-eki/miyazaki/seiunbashi/",
  "/overnight-parking/michi-no-eki/kumamoto/soyokaze-park/"
];
